---

- name: Fail if required nebula settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - nebula_ip
    - nebula_ca_host

#- name: Fail when SMTP settings are missing (and SMTP is enabled by setting host)
#  ansible.builtin.fail:
#    msg: >-
#      You need to define a required configuration setting (`{{ item }}`) to correctly set up email via SMTP.
#  when: "nebula_smtp_host !='' and vars[item] == ''"
#  with_items:
#    - nebula_smtp_from
